# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.280
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]


  # # FIXME: enable when mypy is fixed
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.4.1
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports, --follow-imports=skip]

  # - repo: local
  #   hooks:
  #     - id: unittests
  #       name: run unit tests
  #       entry: python -m pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #       args: [
  #         --doctest-modules
  #       ]
