packages = [
    "pillow==10.2.0",
    "qrcode[pil]==7.4.2",
    "typer==0.15.1",
    "https://cdn.holoviz.org/panel/1.5.5/dist/wheels/bokeh-3.6.2-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.5.5/dist/wheels/panel-1.5.5-py3-none-any.whl",
]
[files]
"./index.py" = "./index.py"
"../../bucket_of_utils/qr/wifi.py" = "bucket_of_utils/qr/wifi.py"
"../../bucket_of_utils/panel_autogenerator/__init__.py" = "bucket_of_utils/panel_autogenerator/__init__.py"
"../../bucket_of_utils/panel_autogenerator/_generate.py" = "bucket_of_utils/panel_autogenerator/_generate.py"
"../../bucket_of_utils/panel_autogenerator/_style.py" = "bucket_of_utils/panel_autogenerator/_style.py"

"https://cdnjs.cloudflare.com/ajax/libs/firacode/6.2.0/ttf/FiraCode-Regular.ttf" = "_static/fonts/FiraCode-Regular.ttf"
